// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "hero-test": {
      name: "hero-test",
      type: "registry:block",
      registryDependencies: undefined,
      files: ["src/registry/section/hero-test.tsx"],
      component: React.lazy(() => import("@/src/registry/registry/section/hero-test.tsx")),
      source: "src/registry/registry/section/hero-test.tsx",
      category: "sections",
      subcategory: "hero",
      chunks: []
    },
    "pricing": {
      name: "pricing",
      type: "registry:block",
      registryDependencies: undefined,
      files: ["src/registry/section/pricing.tsx"],
      component: React.lazy(() => import("@/src/registry/section/pricing.tsx")),
      source: "src/registry/section/pricing.tsx",
      category: "sections",
      subcategory: "marketing",
      chunks: []
    },
    "word-reveal": {
      name: "word-reveal",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/components/prismui/word-reveal.tsx"],
      component: React.lazy(() => import("@/components/prismui/word-reveal.tsx")),
      source: "",
      category: "components",
      subcategory: "animation",
      chunks: []
    },
    "card": {
      name: "card",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/components/prismui/card.tsx"],
      component: React.lazy(() => import("@/components/prismui/card.tsx")),
      source: "",
      category: "components",
      subcategory: "layout",
      chunks: []
    },
    "logo-carousel": {
      name: "logo-carousel",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/components/prismui/logo-carousel.tsx"],
      component: React.lazy(() => import("@/components/prismui/logo-carousel.tsx")),
      source: "",
      category: "components",
      subcategory: "display",
      chunks: []
    },
    "floating-action-panel": {
      name: "floating-action-panel",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/components/prismui/floating-action-panel.tsx"],
      component: React.lazy(() => import("@/components/prismui/floating-action-panel.tsx")),
      source: "",
      category: "components",
      subcategory: "overlay",
      chunks: []
    },
    "hero-badge": {
      name: "hero-badge",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/components/prismui/hero-badge.tsx"],
      component: React.lazy(() => import("@/components/prismui/hero-badge.tsx")),
      source: "",
      category: "components",
      subcategory: "display",
      chunks: []
    },
    "action-button": {
      name: "action-button",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["src/components/prismui/action-button.tsx"],
      component: React.lazy(() => import("@/components/prismui/action-button.tsx")),
      source: "",
      category: "components",
      subcategory: "form",
      chunks: []
    },
  },
}
